version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.9.1
        steps:
            - checkout
            - run:
                name: npm install
                command: npm i
            - run:
                name: npm test
                command: npm test